---
# tasks file for apigee-opdk-yum-packages

- name: Update basic yum os packages
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ yum_os_minimum_packages }}"
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
  when: yum_os_minimum_packages is defined
